[workspace]
members = ["ceramic-kubo-rpc", "ceramic-one", "ceramic"]

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
ceramic-one = { path = "./ceramic-one" }
futures-util = "0.3.26"
iroh-api = { git = "https://github.com/nathanielc/beetle", branch = "expose-api-client" }
iroh-embed = { git = "https://github.com/nathanielc/beetle", branch = "expose-api-client" }
iroh-metrics = { git = "https://github.com/nathanielc/beetle", branch = "expose-api-client" }
iroh-rpc-client = { git = "https://github.com/nathanielc/beetle", branch = "expose-api-client" }
# use same version as Iroh
libipld = "0.15"
# use same version as Iroh
libp2p = { version = "0.50", default-features = false }
# use same version as Iroh
multiaddr = "0.16"
opentelemetry = "0.18.0"
opentelemetry-otlp = "0.11.0"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.34"
tracing-opentelemetry = "0.18"
tracing-subscriber = "0.3.14"
unimock = "0.4.9"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Nathaniel Cook <nvcook42@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/3box/rust-ceramic"
