[package]
name = "libcid_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
#wasm-bindgen = "0.2.74"
libcid.workspace = true
multibase.workspace = true
tokio = {version = "1.25.0", default-features = false, features = []}
