[package]
name = "ceramic-one"
description = "Single binary for Ceramic protocol node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ceramic-set-rec.workspace = true
clap.workspace = true
futures-util.workspace = true
iroh-api.workspace = true
iroh-embed.workspace = true
iroh-metrics.workspace = true
iroh-p2p.workspace = true
iroh-rpc-client.workspace = true
iroh-rpc-types.workspace = true
iroh-util.workspace = true
libipld.workspace = true
libp2p.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
