[package]
name = "custom_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
void.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ceramic.workspace = true

[dependencies.libp2p]
workspace = true
features = [
  "dns",
  "gossipsub",
  "identify",
  "macros",
  "metrics",
  "mplex",
  "noise",
  "ping",
  "relay",
  "request-response",
  "rsa",
  "serde",
  "tcp",
  "tokio",
  "websocket",
  "yamux",
] 

