name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Check fmt
      run: make check-fmt
    - name: Check clippy
      run: make check-clippy
    - name: Run tests
      run: make test

